modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/"

[[mods]]
    modId="conjurerscookbook"
    version="1.5"
    displayName="Conjurer's Cookbook"
    displayURL="https://github.com/"
    updateJSONURL="https://github.com/"
    credits="CosmicParticl"
    authors="CosmicParticl"
    description='''Magical food for your enjoyment!'''

[[dependencies.conjurerscookbook]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.conjurerscookbook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
